FROM node:14-alpine
LABEL Fabian Siatama <fsiatama@gmail.com>

#RUN mkdir -p /usr/src/app

COPY package*.json ./

WORKDIR /usr/src/app

RUN npm install

COPY . /usr/src/app
#RUN npm run compile

# Remove dev dependencies
#RUN npm prune --production

# RUN --mount=type=secret,id=auto-devops-build-secrets . /run/secrets/auto-devops-build-secrets && $COMMAND

ENV PORT 3000
EXPOSE $PORT

#CMD npm start
CMD [ "npm", "run", "dev" ]